/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package second_lab.app;

import second_lab.list.LinkedList;

import static second_lab.utilities.StringUtils.join;
import static second_lab.utilities.StringUtils.split;

import java.util.Arrays;

import org.apache.commons.text.WordUtils;

public class App {
    public static void main(String[] args) {

        double[][] ar = { { 0.00, 2.00, 5.00 }, { 3.21, 0.00, -7.00 }, { 76.34, 1.1, 0.00 } };

        Matrix standart = new Matrix(ar);
        standart.getMatrix();

        Matrix inverse = Matrix.inverse(standart);
        inverse.getMatrix();

        Matrix indent = inverse.multiply(standart);
        indent.getMatrix();

    }
}
